In [1]:
print("ok")

ok

In [2]:
'''
mongodb+srv://<db_username>:a5I8Ii35TzYVL9YY@cluster0.49u1kid.mongodb.net/?appName=Cluster0
'''

'\nmongodb+srv://<db_username>:a5I8Ii35TzYVL9YY@cluster0.49u1kid.mongodb.net/?appName=Cluster0\n'

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("train.csv")
df.head()

,ID,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,...,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,0,1,0,1,0,1,0,1,...,f,?,no,no,Austria,no,6.351166,18 and more,Self,0
1,2,0,0,0,0,0,0,0,0,0,...,m,?,no,no,India,no,2.255185,18 and more,Self,0
2,3,1,1,1,1,1,1,1,1,1,...,m,White-European,no,yes,United States,no,14.851484,18 and more,Self,1
3,4,0,0,0,0,0,0,0,0,0,...,f,?,no,no,United States,no,2.276617,18 and more,Self,0
4,5,0,0,0,0,0,0,0,0,0,...,m,?,no,no,South Africa,no,-4.777286,18 and more,Self,0

In [5]:
df.shape

(800, 22)

In [6]:
df.columns

Index(['ID', 'A1_Score', 'A2_Score', 'A3_Score', 'A4_Score', 'A5_Score',
       'A6_Score', 'A7_Score', 'A8_Score', 'A9_Score', 'A10_Score', 'age',
       'gender', 'ethnicity', 'jaundice', 'austim', 'contry_of_res',
       'used_app_before', 'result', 'age_desc', 'relation', 'Class/ASD'],
      dtype='object')

In [7]:
data=df.to_dict(orient="records")
data

[{'ID': 1,
  'A1_Score': 1,
  'A2_Score': 0,
  'A3_Score': 1,
  'A4_Score': 0,
  'A5_Score': 1,
  'A6_Score': 0,
  'A7_Score': 1,
  'A8_Score': 0,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 38.17274623,
  'gender': 'f',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Austria',
  'used_app_before': 'no',
  'result': 6.351165589,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 2,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 47.7505168,
  'gender': 'm',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'India',
  'used_app_before': 'no',
  'result': 2.255185063,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 3,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 7.380373076,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'yes',
  'contry_of_res': 'United States',
  'used_app_before': 'no',
  'result': 14.85148447,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 4,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 23.56192742,
  'gender': 'f',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'United States',
  'used_app_before': 'no',
  'result': 2.276617372,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 5,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 43.20579044,
  'gender': 'm',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'South Africa',
  'used_app_before': 'no',
  'result': -4.777285747,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 6,
  'A1_Score': 1,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 1,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 31.5279644,
  'gender': 'm',
  'ethnicity': 'Middle Eastern ',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Jordan',
  'used_app_before': 'no',
  'result': 9.562117428,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 7,
  'A1_Score': 1,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 0,
  'age': 28.42797076,
  'gender': 'f',
  'ethnicity': 'Pasifika',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'United Kingdom',
  'used_app_before': 'no',
  'result': 7.984569116,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 8,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 0,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 26.48449442,
  'gender': 'm',
  'ethnicity': 'Black',
  'jaundice': 'no',
  'austim': 'yes',
  'contry_of_res': 'United States',
  'used_app_before': 'no',
  'result': 13.23789759,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 9,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 48.20345856,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Brazil',
  'used_app_before': 'no',
  'result': -1.755773831,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 10,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 0,
  'A10_Score': 1,
  'age': 24.16794517,
  'gender': 'f',
  'ethnicity': 'Others',
  'jaundice': 'yes',
  'austim': 'no',
  'contry_of_res': 'New Zealand',
  'used_app_before': 'no',
  'result': 14.92257038,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 11,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 0,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 21.49703144,
  'gender': 'f',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Canada',
  'used_app_before': 'no',
  'result': 13.83925532,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 12,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 1,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 1,
  'age': 9.044225836,
  'gender': 'm',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'India',
  'used_app_before': 'no',
  'result': 10.73077145,
  'age_desc': '18 and more',
  'relation': 'Relative',
  'Class/ASD': 0},
 {'ID': 13,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 1,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 1,
  'age': 56.00816807,
  'gender': 'm',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Kazakhstan',
  'used_app_before': 'no',
  'result': 0.781776624,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 14,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 0,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 0,
  'age': 21.0875973,
  'gender': 'f',
  'ethnicity': 'Pasifika',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'United Kingdom',
  'used_app_before': 'no',
  'result': 14.44915861,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 15,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 29.14538397,
  'gender': 'm',
  'ethnicity': 'Others',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'United Arab Emirates',
  'used_app_before': 'no',
  'result': 9.798029972,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 16,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 31.27199413,
  'gender': 'f',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Australia',
  'used_app_before': 'no',
  'result': 4.778928938,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 17,
  'A1_Score': 0,
  'A2_Score': 1,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 0,
  'age': 23.73476684,
  'gender': 'm',
  'ethnicity': 'Hispanic',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'India',
  'used_app_before': 'no',
  'result': 6.495259913,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 18,
  'A1_Score': 1,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 1,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 28.63694334,
  'gender': 'f',
  'ethnicity': 'Asian',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'New Zealand',
  'used_app_before': 'no',
  'result': -4.095810694,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 19,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 0,
  'A5_Score': 1,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 0,
  'A10_Score': 1,
  'age': 14.4049851,
  'gender': 'f',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Canada',
  'used_app_before': 'no',
  'result': 1.132228454,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 20,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 72.83887066,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'yes',
  'contry_of_res': 'United States',
  'used_app_before': 'yes',
  'result': 12.28690477,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 21,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 0,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 25.06830214,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'yes',
  'austim': 'yes',
  'contry_of_res': 'United States',
  'used_app_before': 'no',
  'result': 13.99540321,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 22,
  'A1_Score': 0,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 0,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 15.36750123,
  'gender': 'f',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Kazakhstan',
  'used_app_before': 'no',
  'result': 13.9179274,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 23,
  'A1_Score': 1,
  'A2_Score': 0,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 1,
  'age': 41.95517061,
  'gender': 'm',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Ukraine',
  'used_app_before': 'no',
  'result': 5.094295638,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 24,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 0,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 21.05567436,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'yes',
  'contry_of_res': 'United States',
  'used_app_before': 'no',
  'result': 13.68671927,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 25,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 14.12910836,
  'gender': 'm',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'New Zealand',
  'used_app_before': 'no',
  'result': 5.823938278,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 26,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 1,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 54.49860242,
  'gender': 'm',
  'ethnicity': 'Asian',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'United Arab Emirates',
  'used_app_before': 'no',
  'result': 2.404298689,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 27,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 26.59264047,
  'gender': 'm',
  'ethnicity': 'Asian',
  'jaundice': 'yes',
  'austim': 'no',
  'contry_of_res': 'United States',
  'used_app_before': 'no',
  'result': 7.055674924,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 28,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 26.42977485,
  'gender': 'm',
  'ethnicity': 'Middle Eastern ',
  'jaundice': 'yes',
  'austim': 'no',
  'contry_of_res': 'Iraq',
  'used_app_before': 'no',
  'result': -2.612312227,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 29,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 12.84159731,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'France',
  'used_app_before': 'no',
  'result': 9.612488335,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 30,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 9.662208553,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'yes',
  'contry_of_res': 'United Kingdom',
  'used_app_before': 'no',
  'result': 15.77071475,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 31,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 30.50058819,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Malaysia',
  'used_app_before': 'no',
  'result': 13.18953139,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 32,
  'A1_Score': 0,
  'A2_Score': 1,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 74.87051104,
  'gender': 'f',
  'ethnicity': 'Asian',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Jordan',
  'used_app_before': 'no',
  'result': 2.412387021,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 33,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 1,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 1,
  'age': 26.07964814,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Viet Nam',
  'used_app_before': 'no',
  'result': 5.405741271,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 34,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 0,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 67.00819233,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'yes',
  'austim': 'no',
  'contry_of_res': 'New Zealand',
  'used_app_before': 'no',
  'result': 11.64728066,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 35,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 22.46984114,
  'gender': 'm',
  'ethnicity': 'Asian',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Brazil',
  'used_app_before': 'no',
  'result': 10.65086564,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 36,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 0,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 30.94822637,
  'gender': 'f',
  'ethnicity': 'White-European',
  'jaundice': 'yes',
  'austim': 'yes',
  'contry_of_res': 'United States',
  'used_app_before': 'no',
  'result': 15.11245422,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 37,
  'A1_Score': 1,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 0,
  'A10_Score': 1,
  'age': 24.92914563,
  'gender': 'm',
  'ethnicity': '?',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Australia',
  'used_app_before': 'no',
  'result': 7.056010418,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 38,
  'A1_Score': 0,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 0,
  'A5_Score': 1,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 24.94160486,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Egypt',
  'used_app_before': 'no',
  'result': 10.83267415,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 39,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 11.88213606,
  'gender': 'm',
  'ethnicity': 'Turkish',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'United Kingdom',
  'used_app_before': 'no',
  'result': 13.40935439,
  'age_desc': '18 and more',
  'relation': 'Parent',
  'Class/ASD': 0},
 {'ID': 40,
  'A1_Score': 0,
  'A2_Score': 0,
  'A3_Score': 0,
  'A4_Score': 0,
  'A5_Score': 0,
  'A6_Score': 0,
  'A7_Score': 0,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 0,
  'age': 26.75778566,
  'gender': 'm',
  'ethnicity': 'Asian',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Jordan',
  'used_app_before': 'no',
  'result': 3.451321955,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 41,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 0,
  'A9_Score': 0,
  'A10_Score': 1,
  'age': 44.32227347,
  'gender': 'f',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'Netherlands',
  'used_app_before': 'no',
  'result': 11.34651463,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 42,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 0,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 74.53450864,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'United Kingdom',
  'used_app_before': 'no',
  'result': 7.387992163,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 0},
 {'ID': 43,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 23.58363906,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'yes',
  'austim': 'no',
  'contry_of_res': 'United States',
  'used_app_before': 'no',
  'result': 14.064242,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 44,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 0,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 25.64110026,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'no',
  'austim': 'no',
  'contry_of_res': 'United States',
  'used_app_before': 'no',
  'result': 15.07862345,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 45,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 1,
  'A4_Score': 1,
  'A5_Score': 1,
  'A6_Score': 1,
  'A7_Score': 1,
  'A8_Score': 1,
  'A9_Score': 1,
  'A10_Score': 1,
  'age': 22.57022313,
  'gender': 'm',
  'ethnicity': 'White-European',
  'jaundice': 'yes',
  'austim': 'yes',
  'contry_of_res': 'United States',
  'used_app_before': 'yes',
  'result': 15.16591026,
  'age_desc': '18 and more',
  'relation': 'Self',
  'Class/ASD': 1},
 {'ID': 46,
  'A1_Score': 1,
  'A2_Score': 1,
  'A3_Score': 0,

In [8]:
len(data)

800

In [9]:
DB_NAME="Autism"
COLLECTION_NAME = "Autism_data"
CONNECTION_URL="mongodb+srv://ggsamah0_db_user:a5I8Ii35TzYVL9YY@cluster0.49u1kid.mongodb.net/?appName=Cluster0"

In [10]:
print(CONNECTION_URL)

mongodb+srv://ggsamah0_db_user:a5I8Ii35TzYVL9YY@cluster0.49u1kid.mongodb.net/?appName=Cluster0

In [11]:
import pymongo
import certifi

In [16]:
Client=pymongo.MongoClient(CONNECTION_URL, tlsCAFile=certifi.where(), serverSelectionTimeoutMS = 30000)
Data_base = Client[DB_NAME]
collection1 = Data_base[COLLECTION_NAME]
rec = collection1.insert_many(data)

In [15]:
collection1.count_documents({})

1600

In [17]:
records = collection1.find()
records

In [18]:
for i,j in enumerate(records):
    print(f"{i}:{j}")

0:{'_id': ObjectId('6aac328691c5be184890d1fb'), 'ID': 3, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 7.380373076, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'no', 'austim': 'yes', 'contry_of_res': 'United States', 'used_app_before': 'no', 'result': 14.85148447, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
1:{'_id': ObjectId('6aac328691c5be184890d1fd'), 'ID': 5, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 0, 'age': 43.20579044, 'gender': 'm', 'ethnicity': '?', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'South Africa', 'used_app_before': 'no', 'result': -4.777285747, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
2:{'_id': ObjectId('6aac328691c5be184890d200'), 'ID': 8, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 1, 'age': 26.48449442, 'gender': 'm', 'ethnicity': 'Black', 'jaundice': 'no', 'austim': 'yes', 'contry_of_res': 'United States', 'used_app_before': 'no', 'result': 13.23789759, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
3:{'_id': ObjectId('6aac328691c5be184890d202'), 'ID': 10, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 1, 'age': 24.16794517, 'gender': 'f', 'ethnicity': 'Others', 'jaundice': 'yes', 'austim': 'no', 'contry_of_res': 'New Zealand', 'used_app_before': 'no', 'result': 14.92257038, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
4:{'_id': ObjectId('6aac328691c5be184890d203'), 'ID': 11, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 1, 'age': 21.49703144, 'gender': 'f', 'ethnicity': '?', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Canada', 'used_app_before': 'no', 'result': 13.83925532, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
5:{'_id': ObjectId('6aac328691c5be184890d20a'), 'ID': 18, 'A1_Score': 1, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 1, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 0, 'age': 28.63694334, 'gender': 'f', 'ethnicity': 'Asian', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'New Zealand', 'used_app_before': 'no', 'result': -4.095810694, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
6:{'_id': ObjectId('6aac328691c5be184890d211'), 'ID': 25, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 0, 'age': 14.12910836, 'gender': 'm', 'ethnicity': '?', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'New Zealand', 'used_app_before': 'no', 'result': 5.823938278, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
7:{'_id': ObjectId('6aac328691c5be184890d219'), 'ID': 33, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 1, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 1, 'age': 26.07964814, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Viet Nam', 'used_app_before': 'no', 'result': 5.405741271, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
8:{'_id': ObjectId('6aac328691c5be184890d21a'), 'ID': 34, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 1, 'age': 67.00819233, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'yes', 'austim': 'no', 'contry_of_res': 'New Zealand', 'used_app_before': 'no', 'result': 11.64728066, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
9:{'_id': ObjectId('6aac328691c5be184890d21b'), 'ID': 35, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 0, 'age': 22.46984114, 'gender': 'm', 'ethnicity': 'Asian', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Brazil', 'used_app_before': 'no', 'result': 10.65086564, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
10:{'_id': ObjectId('6aac328691c5be184890d21c'), 'ID': 36, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 1, 'age': 30.94822637, 'gender': 'f', 'ethnicity': 'White-European', 'jaundice': 'yes', 'austim': 'yes', 'contry_of_res': 'United States', 'used_app_before': 'no', 'result': 15.11245422, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
11:{'_id': ObjectId('6aac328691c5be184890d21e'), 'ID': 38, 'A1_Score': 0, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 0, 'A5_Score': 1, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 24.94160486, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Egypt', 'used_app_before': 'no', 'result': 10.83267415, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
12:{'_id': ObjectId('6aac328691c5be184890d221'), 'ID': 41, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 1, 'age': 44.32227347, 'gender': 'f', 'ethnicity': 'White-European', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Netherlands', 'used_app_before': 'no', 'result': 11.34651463, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
13:{'_id': ObjectId('6aac328691c5be184890d226'), 'ID': 46, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 1, 'age': 35.73551276, 'gender': 'm', 'ethnicity': '?', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'France', 'used_app_before': 'no', 'result': 5.903541182, 'age_desc': '18 and more', 'relation': '?', 'Class/ASD': 0}
14:{'_id': ObjectId('6aac328691c5be184890d227'), 'ID': 47, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 0, 'age': 22.41443272, 'gender': 'm', 'ethnicity': 'Middle Eastern ', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Jordan', 'used_app_before': 'no', 'result': -0.148261674, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
15:{'_id': ObjectId('6aac328691c5be184890d232'), 'ID': 58, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 0, 'age': 48.35947059, 'gender': 'f', 'ethnicity': 'Middle Eastern ', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'India', 'used_app_before': 'no', 'result': 0.602478061, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
16:{'_id': ObjectId('6aac328691c5be184890d234'), 'ID': 60, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 0, 'A5_Score': 1, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 0, 'age': 21.53439758, 'gender': 'm', 'ethnicity': 'Others', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Australia', 'used_app_before': 'no', 'result': 8.631819037, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
17:{'_id': ObjectId('6aac328691c5be184890d23c'), 'ID': 68, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 17.52426083, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Viet Nam', 'used_app_before': 'no', 'result': 3.971813502, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
18:{'_id': ObjectId('6aac328691c5be184890d23f'), 'ID': 71, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 19.60257605, 'gender': 'm', 'ethnicity': 'Black', 'jaundice': 'yes', 'austim': 'no', 'contry_of_res': 'United Kingdom', 'used_app_before': 'no', 'result': 13.55572805, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
19:{'_id': ObjectId('6aac328691c5be184890d241'), 'ID': 73, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 1, 'age': 42.20076431, 'gender': 'm', 'ethnicity': '?', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'AmericanSamoa', 'used_app_before': 'no', 'result': -0.678711276, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
20:{'_id': ObjectId('6aac328691c5be184890d253'), 'ID': 91, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 1, 'age': 23.51256271, 'gender': 'm', 'ethnicity': 'Others', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'New Zealand', 'used_app_before': 'no', 'result': 8.345052237, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
21:{'_id': ObjectId('6aac328691c5be184890d257'), 'ID': 95, 'A1_Score': 0, 'A2_Score': 1, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 0, 'age': 6.452045955, 'gender': 'f', 'ethnicity': 'Middle Eastern ', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'United Arab Emirates', 'used_app_before': 'no', 'result': 13.02228493, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
22:{'_id': ObjectId('6aac328691c5be184890d258'), 'ID': 96, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 1, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 1, 'age': 24.33664251, 'gender': 'f', 'ethnicity': 'Middle Eastern ', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'France', 'used_app_before': 'no', 'result': 7.165592846, 'age_desc': '18 and more', 'relation': '?', 'Class/ASD': 0}
23:{'_id': ObjectId('6aac328691c5be184890d25e'), 'ID': 102, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 0, 'age': 25.87254066, 'gender': 'm', 'ethnicity': '?', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'India', 'used_app_before': 'no', 'result': 0.517169315, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
24:{'_id': ObjectId('6aac328691c5be184890d262'), 'ID': 106, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 34.77715118, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'United States', 'used_app_before': 'no', 'result': 12.81216575, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
25:{'_id': ObjectId('6aac328691c5be184890d266'), 'ID': 110, 'A1_Score': 0, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 6.10646724, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'United States', 'used_app_before': 'no', 'result': 13.83450996, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
26:{'_id': ObjectId('6aac328691c5be184890d26f'), 'ID': 119, 'A1_Score': 1, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 0, 'age': 29.56542236, 'gender': 'm', 'ethnicity': 'Middle Eastern ', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Jordan', 'used_app_before': 'no', 'result': 13.3826979, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
27:{'_id': ObjectId('6aac328691c5be184890d273'), 'ID': 123, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 0, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 1, 'age': 22.9647067, 'gender': 'f', 'ethnicity': 'White-European', 'jaundice': 'no', 'austim': 'yes', 'contry_of_res': 'Bolivia', 'used_app_before': 'no', 'result': 10.74987544, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
28:{'_id': ObjectId('6aac328691c5be184890d276'), 'ID': 126, 'A1_Score': 1, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 0, 'age': 11.44370159, 'gender': 'f', 'ethnicity': '?', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'United States', 'used_app_before': 'no', 'result': 8.70747756, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
29:{'_id': ObjectId('6aac328691c5be184890d279'), 'ID': 129, 'A1_Score': 1, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 0, 'age': 8.590131092, 'gender': 'm', 'ethnicity': 'Asian', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'New Zealand', 'used_app_before': 'no', 'result': 11.51435907, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
30:{'_id': ObjectId('6aac328691c5be184890d27c'), 'ID': 132, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 28.48610351, 'gender': 'm', 'ethnicity': '?', 'jaundice': 'no', 'austim': 'yes', 'contry_of_res': 'New Zealand', 'used_app_before': 'no', 'result': -1.358063873, 'age_desc': '18 and more', 'relation': 'Parent', 'Class/ASD': 0}
31:{'_id': ObjectId('6aac328691c5be184890d284'), 'ID': 140, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 49.35705181, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'yes', 'austim': 'no', 'contry_of_res': 'New Zealand', 'used_app_before': 'yes', 'result': 6.0629001, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
32:{'_id': ObjectId('6aac328691c5be184890d285'), 'ID': 141, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 1, 'age': 27.546446, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'yes', 'austim': 'no', 'contry_of_res': 'Armenia', 'used_app_before': 'no', 'result': 11.80277865, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
33:{'_id': ObjectId('6aac328691c5be184890d286'), 'ID': 142, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 0, 'age': 21.42575616, 'gender': 'f', 'ethnicity': 'South Asian', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'United Arab Emirates', 'used_app_before': 'no', 'result': 6.574095516, 'age_desc': '18 and more', 'relation': '?', 'Class/ASD': 0}
34:{'_id': ObjectId('6aac328691c5be184890d28c'), 'ID': 148, 'A1_Score': 0, 'A2_Score': 1, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 0, 'age': 19.45372943, 'gender': 'm', 'ethnicity': '?', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Serbia', 'used_app_before': 'no', 'result': -1.388358341, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
35:{'_id': ObjectId('6aac328691c5be184890d29c'), 'ID': 164, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 1, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 0, 'age': 17.00184669, 'gender': 'f', 'ethnicity': '?', 'jaundice': 'yes', 'austim': 'no', 'contry_of_res': 'India', 'used_app_before': 'no', 'result': 5.593677238, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
36:{'_id': ObjectId('6aac328691c5be184890d29e'), 'ID': 166, 'A1_Score': 1, 'A2_Score': 0, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 1, 'age': 17.43356002, 'gender': 'm', 'ethnicity': 'Turkish', 'jaundice': 'no', 'austim': 'yes', 'contry_of_res': 'Sri Lanka', 'used_app_before': 'no', 'result': 13.4727669, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
37:{'_id': ObjectId('6aac328691c5be184890d2a1'), 'ID': 169, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 0, 'A9_Score': 0, 'A10_Score': 0, 'age': 32.02799875, 'gender': 'f', 'ethnicity': 'Others', 'jaundice': 'yes', 'austim': 'no', 'contry_of_res': 'Australia', 'used_app_before': 'no', 'result': 5.714541497, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
38:{'_id': ObjectId('6aac328691c5be184890d2a2'), 'ID': 170, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 20.61060104, 'gender': 'm', 'ethnicity': 'White-European', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'United States', 'used_app_before': 'no', 'result': 11.83426736, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
39:{'_id': ObjectId('6aac328691c5be184890d2af'), 'ID': 183, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 0, 'age': 35.15143448, 'gender': 'f', 'ethnicity': 'Turkish', 'jaundice': 'yes', 'austim': 'no', 'contry_of_res': 'United Kingdom', 'used_app_before': 'no', 'result': 6.670124809, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
40:{'_id': ObjectId('6aac328691c5be184890d2b0'), 'ID': 184, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 48.16365726, 'gender': 'm', 'ethnicity': 'Black', 'jaundice': 'no', 'austim': 'yes', 'contry_of_res': 'Australia', 'used_app_before': 'no', 'result': 13.74766675, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
41:{'_id': ObjectId('6aac328691c5be184890d2b4'), 'ID': 188, 'A1_Score': 0, 'A2_Score': 0, 'A3_Score': 0, 'A4_Score': 0, 'A5_Score': 0, 'A6_Score': 0, 'A7_Score': 0, 'A8_Score': 1, 'A9_Score': 0, 'A10_Score': 1, 'age': 25.21724716, 'gender': 'm', 'ethnicity': 'Middle Eastern ', 'jaundice': 'no', 'austim': 'no', 'contry_of_res': 'Austria', 'used_app_before': 'no', 'result': 12.73761891, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}
42:{'_id': ObjectId('6aac328691c5be184890d2ba'), 'ID': 194, 'A1_Score': 1, 'A2_Score': 0, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 1, 'A9_Score': 1, 'A10_Score': 1, 'age': 54.01025251, 'gender': 'f', 'ethnicity': 'White-European', 'jaundice': 'yes', 'austim': 'no', 'contry_of_res': 'Jordan', 'used_app_before': 'no', 'result': 12.79872393, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 1}
43:{'_id': ObjectId('6aac328691c5be184890d2c3'), 'ID': 203, 'A1_Score': 1, 'A2_Score': 1, 'A3_Score': 1, 'A4_Score': 1, 'A5_Score': 1, 'A6_Score': 1, 'A7_Score': 1, 'A8_Score': 0, 'A9_Score': 1, 'A10_Score': 1, 'age': 22.61007244, 'gender': 'm', 'ethnicity': 'Others', 'jaundice': 'no', 'austim': 'yes', 'contry_of_res': 'United Kingdom', 'used_app_before': 'no', 'result': 3.025562749, 'age_desc': '18 and more', 'relation': 'Self', 'Class/ASD': 0}

In [19]:
df=pd.DataFrame(list(collection1.find()))
df.head()

,_id,ID,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,...,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,6aac328691c5be184890d1fb,3,1,1,1,1,1,1,1,1,...,m,White-European,no,yes,United States,no,14.851484,18 and more,Self,1
1,6aac328691c5be184890d1fd,5,0,0,0,0,0,0,0,0,...,m,?,no,no,South Africa,no,-4.777286,18 and more,Self,0
2,6aac328691c5be184890d200,8,1,1,1,1,1,1,1,0,...,m,Black,no,yes,United States,no,13.237898,18 and more,Self,1
3,6aac328691c5be184890d202,10,0,0,0,0,0,0,0,1,...,f,Others,yes,no,New Zealand,no,14.922570,18 and more,Self,0
4,6aac328691c5be184890d203,11,1,1,1,1,1,1,1,0,...,f,?,no,no,Canada,no,13.839255,18 and more,Self,0

In [ ]:
if "_id" in df.columns.to_list():
    df=df.drop(columns=["_id"],axis=1)

In [ ]:
df.head()

,ID,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,...,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,age_desc,relation,Class/ASD
0,1,1,0,1,0,1,0,1,0,1,...,f,?,no,no,Austria,no,6.351166,18 and more,Self,0
1,2,0,0,0,0,0,0,0,0,0,...,m,?,no,no,India,no,2.255185,18 and more,Self,0
2,3,1,1,1,1,1,1,1,1,1,...,m,White-European,no,yes,United States,no,14.851484,18 and more,Self,1
3,4,0,0,0,0,0,0,0,0,0,...,f,?,no,no,United States,no,2.276617,18 and more,Self,0
4,5,0,0,0,0,0,0,0,0,0,...,m,?,no,no,South Africa,no,-4.777286,18 and more,Self,0